name: Build PurpurTracker
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply patches
        run: ./gradlew applyPatches
      - name: Build
        run: ./gradlew paperclip
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Java 11 Build
          path: ./*.jar
